### ISSUE TITLE
ModuleNotFoundError: No module named 'tools'

### ISSUE THREAD

**Issue by AlanHootman** [ZhihaoDU/speech_feature_extractor#1]
when i was run ams_extractor.py,some errors was show:
`Traceback (most recent call last):
  File "/Users/jhm/Desktop/Speech_Separation/code/speech_feature_extractor-master/ams_extractor.py", line 4, in <module>
    from feature_extractor import stft_extractor
  File "/Users/jhm/Desktop/Speech_Separation/code/speech_feature_extractor-master/feature_extractor.py", line 4, in <module>
    from scikits.talkbox import lpc
  File "/Users/jhm/anaconda/lib/python3.6/site-packages/scikits/talkbox/__init__.py", line 3, in <module>
    from tools import *
ModuleNotFoundError: No module named 'tools'`
i want konw what is the "tools" and how to solve it.
anyone can help me?

**Comment by superhail** [comment]
I met this problem too, have you solved it ?

**Comment by jiaxp3144** [comment]
this is caused by the scikits.talkbox package. it seems that scikits.talkbox cannot work properly with python 3.x. the scikits.talkbox is imported to calc lpc for rasta-plp, so if you only need ams feature, just delete the releted codes in feature_extractor.py and it will work properly.

**Comment by ZhihaoDU** [comment]
jiaxp3144 is right, thanks @jiaxp3144
